language: php

php:
  - 5.5

services:
  - mysql

before_script:
    - mysql -e 'create database symfonyblog;'
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - composer self-update
    - composer install --dev --no-interaction --prefer-source
    - app/console cache:warmup --env=test --quiet

script:
  - app/console doctrine:schema:update --force
  - app/console hautelook_alice:doctrine:fixtures:load --append
  - phpunit -c app/ --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover